### PR TITLE
Rebuild pyyaml 5.4.1 for python 3.10 and 3.11

### PR DESCRIPTION
**Pull request by akabanovs**

### CODE REVIEW

**Review by skupr-anaconda — APPROVED** [review]
LGTM

**Comment by akabanovs** [comment]
Not sure what to do about the linter error:
ERROR: /tmp/abs_4acddnll4i/clone/recipe/meta.yaml:22: yaml_load_failure: The recipe could not be loaded by yaml

This is probably due to the use of multi line syntax - >- in the recipe.  Is it okay to keep it like this?

**Review by varlackc — APPROVED** [review]
LGTM

**Review by M-Waszkiewicz-Anaconda — APPROVED** [review]
LGTM

**Pull request merged**
